### ISSUE TITLE
flag enable-leader-election not supported any longer

### ISSUE THREAD

**Issue by henderiw** [kubernetes-csi/csi-driver-nfs#115]
we should update the charts to comply to the latest csi-provisioner image
possible fix:

containers:
        - name: csi-provisioner
          image: "{{ .Values.image.csiProvisioner.repository }}:{{ .Values.image.csiProvisioner.tag }}"
          args:
            - "-v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            #- "--leader-election-type=leases"

**Comment by andyzhangx** [comment]
the csi-provisioiner is already using v2.0.4 which is a relatively new image:
https://github.com/kubernetes-csi/csi-driver-nfs/blob/683838d7bb83b62b8763a4661b315203b8005b52/charts/latest/csi-driver-nfs/values.yaml#L6-L8

https://github.com/kubernetes-csi/csi-driver-nfs/blob/683838d7bb83b62b8763a4661b315203b8005b52/charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml#L28-L33

Usually we don't use latest image since it requires higher k8s version.
