### ISSUE TITLE
Potential concurrency regression introduced by #201

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-csi/csi-driver-nfs#209]
This report is from code inspection only. There is no environment or reproducer.

I believe #201 'remove unnecessary lock' removed a lock which wasn't unnecessary. The fix was for #200. The reporter was doing concurrent mounts, and one would fail with:

Warning FailedMount 3m40s (x1662 over 48m) kubelet MountVolume.SetUp failed for volume "clearml-agent-caching" : rpc error: code = Aborted desc = An operation with the given Volume ID shaked-test1 already exists

This is the error generated when we fail to TryAcquire in NodePublishVolume. However, the returned grpc code Aborted implies a concurrency issue, and the correct behaviour here would be for the caller to retest if the volume is already published and retry if not, possibly with a small wait.

The problem with removing the lock is that we then call mounter.Mount in NodePublish and mount.CleanupMountPoint in NodeUnpublish. These methods do not appear to have been written with concurrency in mind, and I suspect they contain hard-to-reproduce error cases when executed concurrently for the same volume.

I propose we revert this change and instead handle the Aborted error in the caller.

/cc @andyzhangx @jsafrane

**Comment by jsafrane** [comment]
I think kubelet will never call `NodePublish` & `NodeUnpublish` in parallel on the same volume mount. It may do so for the same volume, but in different pods, and they will have different mount points, so there should be no real conflict.

At the same time, kubelet should retry when it gets Aborted. I think the real issue is why the volume is locked for so long - in the issue #200 I see it failed "_x1662 over 48m_". It looks like the lock was never actually released. Do we know why? Is it safe to mount the same volume to a different place if something went wrong the first time?
