### ISSUE TITLE
Can this driver create persistent volumes automatically, when a persistent volume claim request is created ? 

### ISSUE THREAD

**Issue by ghost** [kubernetes-csi/csi-driver-nfs#70]
This scenario is use full in case of stateful set deployments where VolumeClaimTempletes are created
if this possible , please let me know how to implement it 
Thank You

**Comment by msau42** [comment]
createvolume support was recently added in https://github.com/kubernetes-csi/csi-driver-nfs/pull/53. It creates subdirectories from an existing nfs server. Does that address your use case?

**Comment by lordcf** [comment]
I am using CFCR cluster with AWS as IaaS and EFS as persistent volume storage
earlier i was using efs-provisioner to manage storage request.
What I want is when ever a persistent volume claim request is made by user , efs driver should automatically create persistent volume object for it without any manual intervention 
Is that possible?
As of now we have to create a PV after deploying driver and in pv  object we specify efs id :

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfsplugin
  labels:
    name: data-nfsplugin
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  mountOptions:
    - nfsvers=4.1
  capacity:
    storage: 100Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: fs-xxx
    volumeAttributes:
      server: fs-xxxx.efs.us-east-1.amazonaws.com
      share: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfsplugin
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  selector:
    matchLabels:
      name: "data-nfsplugin"
  resources:
    requests:
      storage: 100Gi


*** this is the sample file we need to create now , where we provide efs is and server name in persistent volume object and then create claim object 
I want to provide efs details in efs driver it self so that  persistent volume objects are created dynamically whenever claim request is made

**Comment by msau42** [comment]
For efs, my understanding is it requires a special mount.efs, which won't work with this driver which is mainly for general nfs servers. I would suggest asking in https://github.com/kubernetes-sigs/aws-efs-csi-driver

**Comment by lordcf** [comment]
hey @msau42 than you for your response. In our case we are using CFCR cluster and as far as I now aws-efs-csi driver is specific to aws eks cluster

**Comment by msau42** [comment]
The efs driver can be used in any aws based Kubernetes ctuster

**Comment by lordcf** [comment]
Hi @msau42  , I downloaded the latest version of this repo with create volume changes and tried to deploy but controller pods are going into crashloop backoff state with  following logs  on csi-provisioner and liveliness container
1 connection.go:170] Still connecting to unix:///csi/csi.sock

**Comment by msau42** [comment]
does the nfsplugin have any error messages? Are you using canary image?

**Comment by lordcf** [comment]
Hi @msau42 above issue is resolved by changes mount paths. but how will this create persistent volume on persistent volume claim request

**Comment by andyzhangx** [comment]
> Hi @msau42 above issue is resolved by changes mount paths. but how will this create persistent volume on persistent volume claim request. In you example file of storage class i have specified my aws efs server by pv is not not getting created and pod is going into pending state with error
> pod has unbound immediate PersistentVolumeClaims
> 
> ## storage class fie looks like this
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
> name: nfs-csi
> provisioner: nfs.csi.k8s.io
> parameters:
> server: fs-xxxx.efs.us-east-1.amazonaws.com
> share: /
> accessModes: ReadWriteOnce
> reclaimPolicy: Retain # only retain is supported
> volumeBindingMode: Immediate
> mountOptions:
> 
> * hard
> * nfsvers=4.1
> 
> I want to store my data on EFS and not on local storage , so where should I specify my efs id
> and can you please give a detailed read me file on what steps to be followed , what is use of controller fie if provisioning is done by nfs-server.yaml

@lordcf could you make sure your nfs server config is correct? You could manually check by `mount -v -t nfs -o ... nfs-server:/path mount-path` and if there is error in driver side, check by https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/csi-debug.md#csi-driver-debug-tips
